In [75]:
import numpy as np
import sklearn.model_selection as skm
from pandas import read_csv
import pandas as pd

In [76]:
data = read_csv('data/train.csv')

In [77]:
data.shape

(74111, 29)

In [78]:
data.dtypes


id                          int64
log_price                 float64
property_type              object
room_type                  object
amenities                  object
accommodates                int64
bathrooms                 float64
bed_type                   object
cancellation_policy        object
cleaning_fee                 bool
city                       object
description                object
first_review               object
host_has_profile_pic       object
host_identity_verified     object
host_response_rate         object
host_since                 object
instant_bookable           object
last_review                object
latitude                  float64
longitude                 float64
name                       object
neighbourhood              object
number_of_reviews           int64
review_scores_rating      float64
thumbnail_url              object
zipcode                    object
bedrooms                  float64
beds                      float64
dtype: object

In [79]:
prueba=data[:10]

In [80]:
# from tensorflow.keras.utils import to_categorical

# yprueba=to_categorical(prueba)

In [81]:
# data

In [82]:
df=data.drop(['property_type',              
'room_type',                  
'amenities', 
'bed_type',                   
'cancellation_policy',
'city',                       
'description',                
'first_review',              
'host_has_profile_pic',   
'host_identity_verified',    
'host_response_rate',         
'host_since',                 
'instant_bookable' ,          
'last_review',
'name',                       
'neighbourhood',
'thumbnail_url' ,              
'zipcode'],axis=1)



In [83]:
data= pd.DataFrame(df)
data=data.dropna()
train_data,test_data =skm.train_test_split(data,
                                test_size = 0.25,
                                random_state = 100)
print(type(train_data))
print(train_data.shape)

mitadTrain=int(train_data.shape[0]/2)
train_data, train_targets =  train_data[mitadTrain:],train_data[:mitadTrain] 

train_data=train_data.drop(['log_price'],axis=1)
train_targets = train_targets['log_price']
print(train_data.columns)
data=data.to_numpy()
train_data=train_data.to_numpy()
train_targets=train_targets.to_numpy()

test_data=test_data['log_price']
test_data=test_data.to_numpy()

print(type(train_data))
print(type(test_data))

<class 'pandas.core.frame.DataFrame'>
(42846, 11)
Index(['id', 'accommodates', 'bathrooms', 'cleaning_fee', 'latitude',
       'longitude', 'number_of_reviews', 'review_scores_rating', 'bedrooms',
       'beds'],
      dtype='object')
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [84]:
# train_data,test_data =skm.train_test_split(data,
#                                 test_size = 0.25,
#                                 random_state = 100)

In [85]:
train_data.shape[0]

21423

In [86]:
train_data.shape[1]

10

In [87]:
test_data.shape

(14283,)

In [88]:
train_data= train_data.reshape((train_data.shape[0], train_data.shape[1]))
train_data= train_data.astype("float32") / 255


train_targets= train_targets.reshape((train_targets.shape[0], ))
train_targets= train_targets.astype("float32") / 255

test_data = test_data.reshape((test_data.shape[0], ))
test_data = test_data.astype("float32") / 255

In [89]:
train_data.dtype


dtype('float32')

In [90]:
train_data

array([[6.6764922e+04, 7.8431377e-03, 3.9215689e-03, ..., 3.7647060e-01,
        0.0000000e+00, 3.9215689e-03],
       [4.1361352e+04, 1.1764706e-02, 7.8431377e-03, ..., 3.7254903e-01,
        3.9215689e-03, 7.8431377e-03],
       [1.8947809e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 3.9215689e-03],
       ...,
       [6.3391898e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.8431373e-01,
        3.9215689e-03, 3.9215689e-03],
       [6.8332992e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 7.8431377e-03],
       [6.1212059e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.7254903e-01,
        0.0000000e+00, 3.9215689e-03]], dtype=float32)

In [91]:
test_data.dtype

dtype('float32')

In [92]:
train_data.shape

(21423, 10)

In [93]:
train_data.shape[0]

21423

In [94]:
test_data.shape

(14283,)

In [95]:
lenTargetTrain=train_data.shape[0]*20/100
print(lenTargetTrain)

4284.6


In [96]:
lenTargetTest=test_data.shape[0]*20/100
print(lenTargetTest)

2856.6


In [97]:
train_data.shape[0]/2

10711.5

In [98]:
# mitadTrain=int(train_data.shape[0]/2)
# train_data, train_targets =  train_data[mitadTrain:],train_data[:mitadTrain] 
# test_data, test_targets =  test_data[int(lenTargetTest):], test_data[:int(lenTargetTest)]

In [99]:
# train_data, train_targets =  train_data[int(lenTargetTrain):],train_data[:int(lenTargetTrain)] 
# test_data, test_targets =  test_data[int(lenTargetTest):], test_data[:int(lenTargetTest)]

In [100]:
train_data.shape

(21423, 10)

In [101]:
train_targets.shape

(21423,)

In [102]:
test_data.shape

(14283,)

In [103]:
# test_targets.shape

Normalizing the data

In [104]:
# from sklearn import preprocessing

In [105]:
# scaler = preprocessing.MinMaxScaler()
# scaler.fit(train_data.drop('log_price', axis = 1))

In [106]:
# from tensorflow.keras.utils import to_categorical
# y_train = to_categorical(train_targets)
# y_test = to_categorical(test_targets)

In [107]:
# mean = train_data.mean(axis=0)
# train_data -= mean
# std = train_data.std(axis=0)
# train_data /= std
# test_data -= mean
# test_data /= std

Building your model

In [108]:
from tensorflow import keras
import tensorflow as tf

In [109]:
train_data

array([[6.6764922e+04, 7.8431377e-03, 3.9215689e-03, ..., 3.7647060e-01,
        0.0000000e+00, 3.9215689e-03],
       [4.1361352e+04, 1.1764706e-02, 7.8431377e-03, ..., 3.7254903e-01,
        3.9215689e-03, 7.8431377e-03],
       [1.8947809e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 3.9215689e-03],
       ...,
       [6.3391898e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.8431373e-01,
        3.9215689e-03, 3.9215689e-03],
       [6.8332992e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 7.8431377e-03],
       [6.1212059e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.7254903e-01,
        0.0000000e+00, 3.9215689e-03]], dtype=float32)

In [110]:
train_targets

array([0.01465753, 0.01923637, 0.01592331, ..., 0.01964955, 0.02025406,
       0.01436691], dtype=float32)

In [111]:
model = keras.Sequential([
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(1)
])
model.compile(optimizer="rmsprop", loss="mse", metrics=["mae"])
model.fit(train_data, train_targets, epochs=20, batch_size=128)

Epoch 1/20


168/168 [==============================] - 1s 2ms/step - loss: 926840.5000 - mae: 718.5356
Epoch 2/20
168/168 [==============================] - 0s 1ms/step - loss: 521599.9688 - mae: 587.9747
Epoch 3/20
168/168 [==============================] - 0s 1ms/step - loss: 275399.2500 - mae: 424.5361
Epoch 4/20
168/168 [==============================] - 0s 2ms/step - loss: 152243.1562 - mae: 303.8738
Epoch 5/20
168/168 [==============================] - 0s 2ms/step - loss: 83798.5312 - mae: 241.2176
Epoch 6/20
168/168 [==============================] - 0s 2ms/step - loss: 50186.5938 - mae: 184.6158
Epoch 7/20
168/168 [==============================] - 0s 2ms/step - loss: 30881.6621 - mae: 141.2486
Epoch 8/20
168/168 [==============================] - 0s 2ms/step - loss: 16161.7090 - mae: 104.9159
Epoch 9/20
168/168 [==============================] - 0s 3ms/step - loss: 8940.9609 - mae: 79.0330
Epoch 10/20
168/168 [==============================] - 0s 2ms/step - loss: 7314.8037 - mae: 70.7999


K-fold validation