In [16]:
import numpy as np
import sklearn.model_selection as skm
from pandas import read_csv
import pandas as pd

In [17]:
data = read_csv('data/train.csv')

In [18]:
data.shape

(74111, 29)

In [19]:
data.dtypes


id                          int64
log_price                 float64
property_type              object
room_type                  object
amenities                  object
accommodates                int64
bathrooms                 float64
bed_type                   object
cancellation_policy        object
cleaning_fee                 bool
city                       object
description                object
first_review               object
host_has_profile_pic       object
host_identity_verified     object
host_response_rate         object
host_since                 object
instant_bookable           object
last_review                object
latitude                  float64
longitude                 float64
name                       object
neighbourhood              object
number_of_reviews           int64
review_scores_rating      float64
thumbnail_url              object
zipcode                    object
bedrooms                  float64
beds                      float64
dtype: object

In [20]:
prueba=data[:10]

In [21]:
# from tensorflow.keras.utils import to_categorical

# yprueba=to_categorical(prueba)

In [22]:
# data

In [23]:
df=data.drop(['property_type',              
'room_type',                  
'amenities', 
'bed_type',                   
'cancellation_policy',
'city',                       
'description',                
'first_review',              
'host_has_profile_pic',   
'host_identity_verified',    
'host_response_rate',         
'host_since',                 
'instant_bookable' ,          
'last_review',
'name',                       
'neighbourhood',
'thumbnail_url' ,              
'zipcode'],axis=1)



In [24]:
data= pd.DataFrame(df)
data=data.dropna()
train_data,test_data =skm.train_test_split(data,
                                test_size = 0.25,
                                random_state = 100)
print(type(train_data))
print(train_data.shape)

mitadTrain=int(train_data.shape[0]/2)
train_data, train_targets =  train_data[mitadTrain:],train_data[:mitadTrain] 

train_data=train_data.drop(['log_price'],axis=1)
train_targets = train_targets['log_price']
print(train_data.columns)
data=data.to_numpy()
train_data=train_data.to_numpy()
train_targets=train_targets.to_numpy()


mitadTest=int(test_data.shape[0]/2)
test_data, test_targets =  test_data[mitadTest:],test_data[:mitadTest] 
test_data=test_data.drop(['log_price'],axis=1)
test_targets=test_targets['log_price']
test_data=test_data.to_numpy()
test_targets=test_targets.to_numpy()


print(type(train_data))
print(type(test_data))

<class 'pandas.core.frame.DataFrame'>
(42846, 11)
Index(['id', 'accommodates', 'bathrooms', 'cleaning_fee', 'latitude',
       'longitude', 'number_of_reviews', 'review_scores_rating', 'bedrooms',
       'beds'],
      dtype='object')
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
# train_data,test_data =skm.train_test_split(data,
#                                 test_size = 0.25,
#                                 random_state = 100)

In [26]:
train_data.shape[0]

21423

In [27]:
train_data.shape[1]

10

In [28]:
test_data.shape

(7142, 10)

In [29]:
train_data= train_data.reshape((train_data.shape[0], train_data.shape[1]))
train_data= train_data.astype("float32") / 255


train_targets= train_targets.reshape((train_targets.shape[0], ))
train_targets= train_targets.astype("float32") / 255

test_data = test_data.reshape((test_data.shape[0],test_data.shape[1] ))
test_data = test_data.astype("float32") / 255

test_targets= test_targets.reshape((test_targets.shape[0], ))
test_targets= test_targets.astype("float32") / 255

In [30]:
train_data.dtype


dtype('float32')

In [31]:
train_data

array([[6.6764922e+04, 7.8431377e-03, 3.9215689e-03, ..., 3.7647060e-01,
        0.0000000e+00, 3.9215689e-03],
       [4.1361352e+04, 1.1764706e-02, 7.8431377e-03, ..., 3.7254903e-01,
        3.9215689e-03, 7.8431377e-03],
       [1.8947809e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 3.9215689e-03],
       ...,
       [6.3391898e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.8431373e-01,
        3.9215689e-03, 3.9215689e-03],
       [6.8332992e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 7.8431377e-03],
       [6.1212059e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.7254903e-01,
        0.0000000e+00, 3.9215689e-03]], dtype=float32)

In [32]:
test_data.dtype

dtype('float32')

In [33]:
train_data.shape

(21423, 10)

In [34]:
train_data.shape[0]

21423

In [35]:
test_data.shape

(7142, 10)

In [36]:
lenTargetTrain=train_data.shape[0]*20/100
print(lenTargetTrain)

4284.6


In [37]:
lenTargetTest=test_data.shape[0]*20/100
print(lenTargetTest)

1428.4


In [38]:
train_data.shape[0]/2

10711.5

In [39]:
# mitadTrain=int(train_data.shape[0]/2)
# train_data, train_targets =  train_data[mitadTrain:],train_data[:mitadTrain] 
# test_data, test_targets =  test_data[int(lenTargetTest):], test_data[:int(lenTargetTest)]

In [40]:
# train_data, train_targets =  train_data[int(lenTargetTrain):],train_data[:int(lenTargetTrain)] 
# test_data, test_targets =  test_data[int(lenTargetTest):], test_data[:int(lenTargetTest)]

In [41]:
train_data.shape

(21423, 10)

In [42]:
train_targets.shape

(21423,)

In [43]:
test_data.shape

(7142, 10)

In [44]:
# test_targets.shape

Normalizing the data

In [45]:
# from sklearn import preprocessing

In [46]:
# scaler = preprocessing.MinMaxScaler()
# scaler.fit(train_data.drop('log_price', axis = 1))

In [47]:
# from tensorflow.keras.utils import to_categorical
# y_train = to_categorical(train_targets)
# y_test = to_categorical(test_targets)

In [48]:
# mean = train_data.mean(axis=0)
# train_data -= mean
# std = train_data.std(axis=0)
# train_data /= std
# test_data -= mean
# test_data /= std

Building your model

In [49]:
from tensorflow import keras
import tensorflow as tf

In [50]:
train_data

array([[6.6764922e+04, 7.8431377e-03, 3.9215689e-03, ..., 3.7647060e-01,
        0.0000000e+00, 3.9215689e-03],
       [4.1361352e+04, 1.1764706e-02, 7.8431377e-03, ..., 3.7254903e-01,
        3.9215689e-03, 7.8431377e-03],
       [1.8947809e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 3.9215689e-03],
       ...,
       [6.3391898e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.8431373e-01,
        3.9215689e-03, 3.9215689e-03],
       [6.8332992e+04, 1.1764706e-02, 3.9215689e-03, ..., 3.9215687e-01,
        3.9215689e-03, 7.8431377e-03],
       [6.1212059e+04, 1.5686275e-02, 3.9215689e-03, ..., 3.7254903e-01,
        0.0000000e+00, 3.9215689e-03]], dtype=float32)

In [51]:
train_targets

array([0.01465753, 0.01923637, 0.01592331, ..., 0.01964955, 0.02025406,
       0.01436691], dtype=float32)

In [52]:
model = keras.Sequential([
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(1)
])
model.compile(optimizer="rmsprop", loss="mse", metrics=["mae"])
model.fit(train_data, train_targets, epochs=20, batch_size=128)

Epoch 1/20
168/168 [==============================] - 1s 1ms/step - loss: 1225171.2500 - mae: 836.9160
Epoch 2/20
168/168 [==============================] - 0s 1ms/step - loss: 624845.3750 - mae: 662.1854
Epoch 3/20
168/168 [==============================] - 0s 1ms/step - loss: 323711.4375 - mae: 475.0194
Epoch 4/20
168/168 [==============================] - 0s 2ms/step - loss: 191373.5625 - mae: 361.4431
Epoch 5/20
168/168 [==============================] - 0s 1ms/step - loss: 120162.0000 - mae: 281.2370
Epoch 6/20
168/168 [==============================] - 0s 1ms/step - loss: 66159.0469 - mae: 211.7646
Epoch 7/20
168/168 [==============================] - 0s 1ms/step - loss: 43506.2500 - mae: 172.3705
Epoch 8/20
168/168 [==============================] - 0s 1ms/step - loss: 29856.9434 - mae: 141.3225
Epoch 9/20
168/168 [==============================] - 0s 1ms/step - loss: 20345.4297 - mae: 115.4961
Epoch 10/20
168/168 [==============================] - 0s 1ms/step - loss: 13591.9170

In [53]:
predictions = model.predict(test_data)
predictions[0]

224/224 [==============================] - 0s 830us/step


array([-56.136692], dtype=float32)

In [55]:
if test_data.shape[0]!=test_targets[0]:
    test_data=test_data[:test_data.shape[0]-1]
mse, mae = model.evaluate(test_data, test_targets)
print(f"mae: {mae}")

224/224 [==============================] - 0s 1ms/step - loss: 1367.4790 - mae: 32.5761
mae: 32.576141357421875
